TOKEN_KEY_NOT_VALID = 'Token key is not valid.'
TOKEN_USER_NOT_EXISTS = 'Token user not exists.'
TOKEN_USER_NOT_ACTIVE = 'Token user is not active.'
TOKEN_KEY_EXPIRED = 'Token key is expired.'
TOKEN_HEADER_NOT_VALID = 'Token header is not valid.'
TOKEN_HEADER_PREFIX_NOT_VALID = 'Token header prefix is not valid.'
